spring.application.name=RateLimiter

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5439/paymentengine}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:gateway}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:gateway}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false

jwt.secret=Tf8FelYUyOfv2fmd+NQ5GbwI2BLOi4c9cs7e0MUWKbk=

gateway.upstream.base-url=https://api.example.com
